_backend:
    resource: '@EasyAdminBundle/Controller/'
    type:     annotation
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: en|es|ja
    defaults:
        _locale: '%locale%'

_extranet:
    resource: '@AppBundle/Controller/ExtranetController.php'
    type:     annotation
    prefix:   /extranet

# Ruta de la portada básica del sitio (sin ningún parámetro)
# esta ruta es opcional, ya que la aplicación puede funcionar bien
# solamente con la ruta 'portada' y sus valores por defecto
_portada:
     path:  /
     defaults:
          _controller: AppBundle:Redirect:redirect
          route: portada
          ciudad: '%app.ciudad_por_defecto%'
     requirements:
          _format: html|rss

vuelve:
     path: /vuelve-pronto.{_format}
     defaults:
         _controller: AppBundle:Default:vuelve
         route: vuelve
         _format: html


Extranet:
     resource: '@AppBundle/Resources/config/extranet/routing.yml'
     prefix:   /extranet

 #oferta:
 #     path: /{ciudad}/ofertas/{slug}
 #     defaults:
 #          _controller: AppBundle:Oferta:oferta


#pagina_oferta:
#      path:  /ayuda
#      defaults: { _controller: CuponOfertaBundle:Default:ayuda }
#
#pagina_estatica:
#      path:  /sitio/{pagina}
#      defaults: { _controller: CuponOfertaBundle:Sitio:estatica }

