extranet_portada:
    path:     /
    defaults: { _controller: AppBundle:Extra:portada }


extranet_oferta_nueva:
    path:     /oferta/nueva
    defaults: { _controller: AppBundle:Extra:ofertaNueva }


extranet_oferta_editar:
    path:     /oferta/editar/{id}
    defaults: { _controller: AppBundle:Extra:ofertaEditar }


extranet_oferta_ventas:
    path:     /oferta/ventas/{id}
    defaults: { _controller: AppBundle:Extra:ofertaVentas }


extranet_perfil:
    path:     /perfil
    defaults: { _controller: AppBundle:Extra:perfil }


extranet_login:
    pattern: /login
    defaults: { _controller: AppBundle:Extra:login }


extranet_login_check:
    pattern: /login_check


extranet_logout:
    pattern: /logout


registro_tienda:
    pattern: /registro